# Originally imported via:
#   stubgen {...} -m mlir._mlir_libs._mlir.passmanager
# Local modifications:
#   * Relative imports for cross-module references.
#   * Add __all__

from typing import Any, Optional, Callable

from . import ir as _ir

__all__ = [
    "PassInstrumenter",
    "PassManager"
]

class PassInstrumenter:
    def __init__(self) -> None: ...
    @property
    def runBeforePipeline(self) -> Callable: ...
    @property
    def runAfterPipeline(self) -> Callable: ...
    @property
    def runBeforePass(self) -> Callable: ...
    @property
    def runAfterPass(self) -> Callable: ...
    @property
    def runAfterPassFailed(self) -> Callable: ...
    @property
    def runBeforeAnalysis(self) -> Callable: ...
    @property
    def runAfterAnalysis(self) -> Callable: ...

class PassManager:
    def __init__(self, anchorOp : str, context: Optional[_ir.Context] = None) -> None: ...
    def _CAPICreate(self) -> object: ...
    def _testing_release(self) -> None: ...
    def enable_ir_printing(self) -> None: ...
    def enable_verifier(self, enable: bool) -> None: ...
    @staticmethod
    def parse(pipeline: str, context: Optional[_ir.Context] = None) -> PassManager: ...
    def add(self, pipeline : str) -> None: ...
    def run(self, module: _ir._OperationBase) -> None: ...
    def addInstrumentation(self, instrumenter) -> None: ...
    @property
    def _CAPIPtr(self) -> object: ...
